# This is a basic workflow to help you get started with Actions
# 保存记录
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: CheckOut DrakLight
        run: |
          cd ..
          git clone https://github.com/DarkLight-Long/DarkLight.git
      # for below line: Please use it to checkout your rep, otherwise you have not permission or it shows you that 
      # it can not read Username for 'https://github.com': No such device or address
      - name: CheckOut blog-demo
        uses: actions/checkout@v2.3.5
      - name: Build DarkLight and cp dist/* to demo-blog folder
        run: |
          ls
          pwd
          cd ../DarkLight
          npm install
          npm run build
          /bin/cp -rf dist/* ../blog-demo
          cd ../blog-demo
          pwd
          ls
      - name: Push demo-blog to github rep
        run: |
          cd ../blog-demo
          git config --global user.name "DarkLight-Long"
          git config --global user.email "854590394@qq.com"
          git add ./*
          git commit -m "$(date)"
          git push
      - name: end
        run: |
          echo this ci script is successfully so that i stop it
      
      
