# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: CheckOut Floder
        run: |
          cd ..
          rm -rf ./blog-demo
          git clone https://github.com/DarkLight-Long/DarkLight.git
          git clone https://github.com/DarkLight-Long/blog-demo.git
      - name: Build DarkLight and cp dist/* to demo-blog folder
        run: |
          ls
          pwd
          cd ../DarkLight
          npm install
          npm run build
          /bin/cp -rf dist/* ../blog-demo
          cd ../blog-demo
          pwd
          ls
      - name: Push demo-blog to github rep
        run: |
          cd ../blog-demo
          git config --global user.name "DarkLight-Long"
          git config --global user.email "854590394@qq.com"
          git add ./*
          git commit -m "$(date)"
          git push origin
      
      
